### ISSUE TITLE
need SQL options

### ISSUE THREAD

**Issue by mturnaviotov** [Jaykul/PowerBot#9]
it would be great if there was an easy way for a use ms sql,.oracle, postgres drivers, as entity framework, as example, for addition to SQLite, which used now

**Comment by mturnaviotov** [comment]
in addition - move hardcoded path to SQLite base file into config

**Comment by Jaykul** [comment]
I've no interest in doing database work, and I don't want to add setting up a database server to the configuration that has to be done already. 

Honestly, I don't think bots require a database.

I only added SQLite because it had a PowerShell provider and it's zero-setup (just copy the SQLite module). I could remove it from the bot core and leave it up to the modules you use if you'd rather not have the bot initialize it, but it's a simple test -- the code only runs if you have the SQLite module.
